# Generated by Django 5.0 on 2023-12-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_prof', models.TextField(default='null')),
                ('Command_prof', models.TextField()),
                ('Command_no_of_prof', models.CharField(default='null', max_length=500)),
                ('Command_who_used_prof_user', models.CharField(default='null', max_length=500)),
                ('Command_who_used_prof_channelid', models.CharField(default='null', max_length=500)),
                ('Command_prof_published_at', models.CharField(default='null', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='scraped_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('uploaddate', models.CharField(default='', max_length=250)),
                ('channelid', models.CharField(default='', max_length=250)),
                ('description', models.TextField()),
                ('video_id', models.CharField(default='', max_length=250)),
                ('video_tags', models.TextField()),
                ('view_count', models.CharField(default='', max_length=250)),
                ('like_count', models.CharField(default='', max_length=250)),
                ('comment_count', models.CharField(default='', max_length=250)),
                ('latitude', models.CharField(default='null', max_length=250)),
                ('longitude', models.CharField(default='null', max_length=250)),
                ('locationDescription', models.CharField(default='null', max_length=250)),
                ('thumbnail', models.CharField(default='null', max_length=500)),
                ('profile', models.CharField(default='null', max_length=500)),
                ('simmilar_video', models.TextField(default='null')),
                ('email_scraping_dis', models.TextField(default='null')),
                ('channel_profile_link', models.CharField(default='null', max_length=50)),
                ('channel_Location', models.CharField(default='null', max_length=5)),
                ('channel_custom_url', models.CharField(default='null', max_length=60)),
                ('channel_Default_language', models.CharField(default='null', max_length=10)),
                ('channel_name', models.CharField(default='null', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('password', models.CharField(default='', max_length=65)),
            ],
        ),
    ]
